In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()

In [60]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

<B>Using train_test_split

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

<B>Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

<B>SVM

In [38]:
from sklearn.svm import SVC
sm=SVC()
sm.fit(X_train,y_train)
sm.score(X_test,y_test)

1.0

<B>Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)
dtc.score(X_test,y_test)

0.9666666666666667

<B>Random Forest

In [40]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

<H1>KFold cross validation</H1><br>
<B>Basic example

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

In [19]:
for train_index,test_index in kf.split([0,1,2,3,4,5,6,7,8]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


<B>Use KFold for iris dataset

In [20]:
def get_model(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [22]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
skf_logisticReg=[]
skf_svm=[]
skf_DT=[]
skf_RF=[]

for train_index,test_index in skf.split(irisdataset,iris.target):
    X_train,X_test,y_train,y_test=iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    skf_logisticReg.append(get_model(LogisticRegression(), X_train,X_test,y_train,y_test))
    skf_svm.append(get_model(SVC(), X_train,X_test,y_train,y_test))
    skf_DT.append(get_model(DecisionTreeClassifier(), X_train,X_test,y_train,y_test))
    skf_RF.append(get_model(RandomForestClassifier(), X_train,X_test,y_train,y_test))

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [32]:
skf_logisticReg

[0.98, 0.96, 0.98]

In [33]:
skf_svm

[0.96, 0.98, 0.94]

In [34]:
skf_DT

[0.98, 0.94, 0.96]

In [35]:
skf_RF

[0.98, 0.94, 0.98]

<b>Cross_val_score function

In [57]:
import numpy as np
from sklearn.model_selection import cross_val_score
lrm=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=10)
np.average(lrm)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

0.9733333333333334

In [48]:
svcm=cross_val_score(SVC(),iris.data,iris.target,cv=10)
np.average(svcm)

0.9733333333333334

In [49]:
dtcm=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=10)
np.average(dtcm)

0.96

In [50]:
rfcm=cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=10)
np.average(rfcm)

0.96

In [59]:
rfcm1=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=10)
np.average(rfcm1)

0.9666666666666666

<b>Best score so far is from LogisticRegression and SVM: 0.97344771241830064